<?php
$members=[
    [
        "name"=>"J",
        "img"=>"team-1.jpg",
        "summary"=>"美容師",
        "description"=>"ゴルフとナンパが好き。<br>ナンパが好き。"
    ],
    [
        "name"=>"A",
        "img"=>"team-2.jpg",
        "summary"=>"無職",
        "description"=>"無職。限定好き。<br>地図が読めない。<br>ゴルフスクールに多額の投資。",
    ],
    [
        "name"=>"T",
        "img"=>"team-3.jpg",
        "summary"=>"CTO",
        "description"=>"多忙",
    ],
    [
        "name"=>"N",
        "img"=>"team-4.jpg",
        "summary"=>"飲食店店員",
        "description"=>"ゴルフ意識高い肉好き。ただしメンタルが弱い。<br>108出したので破門の危機。",

    ],
    [
        "name"=>"M",
        "img"=>"team-5.jpg",
        "summary"=>"土偶",
        "description"=>"地球上唯一の縄文時代生まれ。年齢不詳。<br>ゴルフスクールに多額の投資。",
    ],
];
