<?php

$scores=[
    [
        "date"=>"2023/10/24",
        "score"=>[
            [
                "name"=>"J",
                "gross"=>"77",
            ],
            [
                "name"=>"A",
                "gross"=>"79",
            ],
            [
                "name"=>"T",
                "gross"=>"83",
            ],
            [
                "name"=>"N",
                "gross"=>"86",
            ],
        ],
    ],
    [
        "date"=>"2023/11/21",
        "score"=>[
            [
                "name"=>"A",
                "gross"=>"80",
            ],
            [
                "name"=>"T",
                "gross"=>"80",
            ],
            [
                "name"=>"J",
                "gross"=>"84",
            ],
            [
                "name"=>"N",
                "gross"=>"100",
            ],
        ],
    ],
];
